### ISSUE TITLE
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by felix63** [picklepete/pyicloud#112]
I'm trying to use pyicloud but i'm running into some trouble. When starting I get the following. Tried everything!

If anyone has a tip?

pi@domus:~/domoboard$ python server.py -c basic.conf
Traceback (most recent call last):
  File "server.py", line 159, in <module>
    api.init()
  File "/home/pi/domoboard/modules/api.py", line 16, in init
    modules = loadPlugins()
  File "/home/pi/domoboard/modules/api.py", line 39, in loadPlugins
    plugin[name] = imp.load_source(name, plugin_dir + i)
  File "/home/pi/domoboard/plugins/icloud.py", line 3, in <module>
    from pyicloud import PyiCloudService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/__init__.py", line 2, in <module>
    from pyicloud.base import PyiCloudService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/base.py", line 18, in <module>
    from pyicloud.services import (
  File "/usr/local/lib/python2.7/dist-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/services/__init__.py", line 7, in <module>
    from pyicloud.services.account import AccountService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/services/account.py", line 31, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

**Comment by coddingtonbear** [comment]
Just briefly glancing, it sounds like you might not have a new enough version of 'six'; could you try running 'pip install --upgrade 'six' to see if that solves your problem?

**Comment by felix63** [comment]
Thanks.. I tried that. Didn't do anything. Perhaps its two-factor authorization. I am now looking into that option.

**Comment by coddingtonbear** [comment]
It definitely doesn't have anything to do with two-factor-authentication -- that decorator is defined [in the `six` library](https://pythonhosted.org/six/#six.python_2_unicode_compatible).

You might be able to glean a little more information by running the following command at the command-line--

```
python -c 'import six; print six.__version__'
```

What number does it print for you; it *should* print 1.10.0 if six was properly upgraded.

**Comment by squandor** [comment]
to fix this you could try easy_install six instead of pip. otherwise explicit choose the right six version you must install six-1.10.0

**Comment by felix63** [comment]
Fixed. Thanks Coddingtonbear/Squandor!
