### ISSUE TITLE
App-Specific Passwords Fails

### ISSUE THREAD

**Issue by sfanous** [picklepete/pyicloud#122]
Hi,

My iCloud account is setup to use 2FA which I understand is not currently supported by pyicloud. Apple however does offer an excellent alternative called App-Specific Passwords. I generated an App-Specific Password for my Python Script and tried to use it to log-in but got the following errors

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pyicloud\base.py", line 186, in authenticate
    data=json.dumps(data)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pyicloud\base.py", line 99, in request
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Misdirected Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sherif\Desktop\iCloud\icloud.py", line 10, in <module>
    api2 = PyiCloudService('sherif.fanous@icloud.com', 'njlj-qiuc-ddsv-vqrj')
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pyicloud\base.py", line 167, in __init__
    self.authenticate()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\pyicloud\base.py", line 190, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Misdirected Request',))`

Is this feature not supported?

**Comment by torarnv** [comment]
Correct, iCloud.com login can not use app password I'm afraid.
