### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by xiswar** [picklepete/pyicloud#129]
Hello,

Since tuesday 11.Apr.2017 I get this error. Before it was no problem. I did not change anything on my server nor my devices did change.

What could be the problem? thanks for any help.

    api = PyiCloudService(user_email,user_password)
    api.devices
    Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/pyicloud/base.py", line 270, in devices
    self.params
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/pyicloud/services/findmyiphone.py", line 28, in __init__
    self.refresh_client()
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/pyicloud/services/findmyiphone.py", line 44, in refresh_client
    'selectedDevice': 'all',
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
    File "/home/rawsix/.virtualenvs/rawsix/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
    SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

**Comment by xiswar** [comment]
Hello,

I tracked down the problem and it seems there is a problem with the requests package. For now I have found a hack to fix it but it is probably not the safest hack. Here the solution for now:

    pip uninstall -y certifi
    pip install certifi==2015.04.28

Enjoy eastern!

**Comment by Jirmi** [comment]
Hi @xiswar, I'm actually facing same issue as you did. What is strange that the issue appears only on linux machine. On my macbook it works fine. Wondering if it is caused due to some CA certificates missing. I have installed on both machines certifi==2017.4.17.

Did you please manage to find better solution for the issue?
