### ISSUE TITLE
JSONDecodeError when running `api.files.dir()`

### ISSUE THREAD

**Issue by goldcase** [picklepete/pyicloud#140]
Before running `api.files.dir()`, I authenticate and test using `api.devices`. Everything checks out.

Then, I run:

`>>> api.files.dir()`

and get:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyicloud/services/ubiquity.py", line 48, in __getattr__
    return getattr(self.root, attr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyicloud/services/ubiquity.py", line 44, in root
    self._root = self.get_node(0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyicloud/services/ubiquity.py", line 25, in get_node
    return UbiquityNode(self, request.json())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I did some shallow digging and ran:
```
>>> api.files._root is None
True
```

Has anyone seen this before? Is there a fix for this? I tested with python3.6 and python2.7. Let me know if I should provide more info.

**Comment by strycker** [comment]
I'm seeing this for calendar.events() and just opened a separate issue.  Has the API changed on Apple's end?

**Comment by avanalfen** [comment]
I know this is a while after the post but I'm getting this error for 'api.photos.all' and 'api.files.dir()'. I'm using Python 3.6 right now. Is there another version that this works on or is there a workaround that anyone knows before I start digging?

**Comment by chadj** [comment]
The back-end for the files api changed awhile back and needs to be reimplemented. pyicloud can't currently work with iCloud drive files.

@avanalfen This response is late but install directly from github to get a version of pyicloud that works with the new Photo's backend.

```
$ pip install git+https://github.com/picklepete/pyicloud
```

**Comment by Quentame** [comment]
Seems to have the solution in #166.

Please create a new issue if still exists.
