### ISSUE TITLE
[Errno 61] when downloading photos 

### ISSUE THREAD

**Issue by r3ticuli** [picklepete/pyicloud#144]
when running `api.photos` , I receive the following error : 

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    api.photos
  File "python3.6/site-packages/pyicloud/base.py", line 304, in photos
    self.params
  File "python3.6/site-packages/pyicloud/services/photos.py", line 30, in __init__
    params=self.params
  File "python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "python3.6/site-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p22-photosws.icloud.com', port=443): Max retries exceeded with url: ***********************
 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111a526d8>: Failed to establish a new
 connection: [Errno 61] Connection refused',))

```

any ideas?

**Comment by martimarkov** [comment]
Check #137

**Comment by r3ticuli** [comment]
Worked, thanks! I hope this gets merged into master soon.
