### ISSUE TITLE
Cannot import name PyiCloudService

### ISSUE THREAD

**Issue by oculos** [picklepete/pyicloud#154]
Hi,

I install pyicloud with pip, and when I try to import it, or import using `from pyicloud import PyiCloudService`, I got this:

```
>>> import pyicloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/pyicloud/__init__.py", line 2, in <module>
    from pyicloud.base import PyiCloudService
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/pyicloud/base.py", line 7, in <module>
    import requests
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 35, in <module>
    from .request import RequestMethods
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/urllib3/request.py", line 3, in <module>
    from .filepost import encode_multipart_formdata
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/urllib3/filepost.py", line 9, in <module>
    from .fields import RequestField
  File "/Users/francis/gitstuff/testvenv/venv/lib/python2.7/site-packages/urllib3/fields.py", line 2, in <module>
    import email.utils
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/utils.py", line 32, in <module>
    from email._parseaddr import quote
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "calendar.py", line 1, in <module>
    from pyicloud import PyiCloudService
ImportError: cannot import name PyiCloudService
```

Any tip on how to fix it?

**Comment by coddingtonbear** [comment]
Just briefly glancing, it _looks_ like you might be running this from within the `pyicloud` folder.  If you run from outside the `pyicloud` module's folder, I think you'll be ok.  The problem is rooted in how Python identifies which module you actually want when you say something like `import calendar`, and if you happen to be in a folder that has a `calendar.py`, it's very possible that it'll pick the wrong one (as it is in this case).

**Comment by oculos** [comment]
spot on, @coddingtonbear! In fact, I was running from an install on a virtual environment, installed with pip. But you were right - it was all about renaming the file and all works now! Thanks! :D
