### ISSUE TITLE
api.devices leads to PyiCloudAPIResponseError:  (450)

### ISSUE THREAD

**Issue by romba050** [picklepete/pyicloud#156]
Hi,
I am running macOS Sierra and python 3. Trying to read my devices as described in the readme leads to an Error.

>> api.devices

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/pyicloud-master/pyicloud/base.py", line 297, in devices
    self.params
  File "/Applications/pyicloud-master/pyicloud/services/findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "/Applications/pyicloud-master/pyicloud/services/findmyiphone.py", line 44, in refresh_client
    'selectedDevice': 'all',
  File "/usr/local/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Applications/pyicloud-master/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/Applications/pyicloud-master/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError:  (450)

**Comment by jsugg** [comment]
- Same thing here. MacOS Sierra, Python 2.7.10
- Turns out that HTTP status code 450 is "Blocked by Windows Parental Controls (Microsoft)"
- Tried to access the devices with a [PHP piece of code](https://github.com/Neal/FindMyiPhone) I found in GitHub, and worked.
- Google returned just 2 results for this error, this one, and a clone of this in bountysource.com.

Dead end. Any ideas would be welcome.

>>> api.devices
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/base.py", line 297, in devices
    self.params
  File "/Library/Python/2.7/site-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/services/findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "/Library/Python/2.7/site-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/services/findmyiphone.py", line 44, in refresh_client
    'selectedDevice': 'all',
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/Library/Python/2.7/site-packages/pyicloud-0.9.1-py2.7.egg/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError:  (450)

**Comment by jsugg** [comment]
And, suddenly it worked again. I went to the bathroom, came back, and it just worked.

The thing here is.. if I put this into production, it could fail anytime, and we don't know nor the problem nor the solution.

**Comment by takakikazunari** [comment]
Same Behavior under my env (Windows 10/ Python 3.6/ jupyter notebook)
But my Script run well in console (windows cmd).
Perhaps a problem arises if it comes through a browser.

**Comment by Quentame** [comment]
Same behavior here in Docker & in MacOS.

Have you found something to resolve the problem ?

**Comment by Quentame** [comment]
Found a fix
