### ISSUE TITLE
Getting some error: Invalid global session 

### ISSUE THREAD

**Issue by AlexanderWillner** [picklepete/pyicloud#158]
Merged from https://github.com/ndbroadbent/icloud_photos_downloader/issues/29 . Here my stack trace:
```
Traceback (most recent call last):
  File "/home/pi/icloud_photos_downloader/download_photos.py", line 255, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/icloud_photos_downloader/download_photos.py", line 129, in download
    for photo in progress_bar:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 579, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session
```

**Comment by chadj** [comment]
Is this error still occurring to you?  Can you provide any additional information on how to reproduce this problem?

**Comment by fnordahl** [comment]
I'm getting this too. You can reproduce it by downloading a lot of photos, reference: ndbroadbent/icloud_photos_downloader#47

Is there a way for consumers of the library to refresh the session?

**Comment by fnordahl** [comment]
I have found catching `pyicloud.exceptions.PyiCloudAPIResponseError` then calling `PyiCloudService.authenticate()` and re-trying the failed operation to be a effective workaround.

@chadj Do you think this is a good solution or do we need some session refresh functionality here?

**Comment by Quentame** [comment]
No response, gone stale.
