### ISSUE TITLE
I'm getting an error KeyError: u'resJPEGMedRes'

### ISSUE THREAD

**Issue by dmullenaux** [picklepete/pyicloud#162]
Hey guys! Thank you so much for this project! I like having my files in my control, this has done that.

I did come across and error while downloading photos:

`Downloading 6891 original photos and videos to /mnt/mybook4tb/iCloud/ ...
/mnt/mybook4tb/iCloud/2015/05/19/IMG_5571-original.JPG already exists.:  90%|██████████████████████████████████████▋    | 6195/6891 [02:35<00:17, 39.28it/s]Traceback (most recent call last):
  File "./download_photos.py", line 255, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 158, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "./download_photos.py", line 222, in download_photo
    if size not in photo.versions and not force_size and size != 'original':
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 487, in versions
    'size': f['%sRes' % prefix]['value']['size'],
KeyError: u'resJPEGMedRes'
`
I was able to over come this error by editing line 425 and updating the key there. Not sure if it was right or wrong, but it worked for me. 

This is what is working for me now:

`    PHOTO_VERSION_LOOKUP = {
        u"original": u"resOriginal",
        u"medium": u"resJPEGMedRes",
        u"thumb": u"resJPEGThumb"
    }`

https://github.com/picklepete/pyicloud/blob/3899363167c1f782a8b3e90a9e5c2fe881a2cb9b/pyicloud/services/photos.py#L425

**Comment by chadj** [comment]
#163 should fix this

**Comment by cleygraf** [comment]
I can confirm that this solves the issue! Thx!

Please accept into the main branch!

**Comment by Quentame** [comment]
Hope it's not too late 😊, will be in next release !
