### ISSUE TITLE
PyIcloud Error: simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by PythonicCoder101** [picklepete/pyicloud#166]
My Code: 
>>> from pyicloud import PyiCloudService
>>> api = PyiCloudService('xxxxx@icloud.com', 'password')
>>> api.iphone.location()

Error:
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    api.iphone.location()
  File "C:\Users\User\Anaconda3\lib\site-packages\pyicloud\base.py", line 284, in iphone
    return self.devices[0]
  File "C:\Users\User\Anaconda3\lib\site-packages\pyicloud\base.py", line 270, in devices
    self.params
  File "C:\Users\User\Anaconda3\lib\site-packages\pyicloud\services\findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "C:\Users\User\Anaconda3\lib\site-packages\pyicloud\services\findmyiphone.py", line 49, in refresh_client
    self.response = req.json()
  File "C:\Users\User\Anaconda3\lib\site-packages\requests\models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "C:\Users\User\Anaconda3\lib\site-packages\simplejson\__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\Anaconda3\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\User\Anaconda3\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PythonicCoder101** [comment]
I solved it

**Comment by YibaiMeng** [comment]
I've encountered similar error for `files` attribute. Sample code:
```
icloud = authenticate(my_user_name, my_password)
# everything else works fine, could see my contact, etc,
icloud.files.dir()
```
Now there's a problem:
```
  File "pyicloud_test.py", line 38, in <module>
    icloud.files.dir()
  File "/usr/local/lib/python3.6/dist-packages/pyicloud/services/ubiquity.py", line 48, in __getattr__
    return getattr(self.root, attr)
  File "/usr/local/lib/python3.6/dist-packages/pyicloud/services/ubiquity.py", line 44, in root
    self._root = self.get_node(0)
  File "/usr/local/lib/python3.6/dist-packages/pyicloud/services/ubiquity.py", line 25, in get_node
    return UbiquityNode(self, request.json())
  File "/home/mengyibai/.local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Something wrong for the `simplejson` library? The error message is identical with the above problem.

**Comment by TayyabaAmbreen** [comment]
Can you tell me how did you solve it?

**Comment by coddingtonbear** [comment]
Just to make sure everybody here is on the same page -- that error message is being emitted from `simplejson` because a response from iCloud that this library expects to be JSON is not actually JSON ; it's not actually an indication of a problem in `simplejson` itself.

**Comment by PythonicCoder101** [comment]
Before the api.location(),
Try the command api.authenticate().
Before I had the same issue as you but I added it and it worked for me!

**Comment by ikrambennasrbennasr** [comment]
Hello ; please i run this code : 

data = json.dumps({'sl':5.84,'sw':3.0,'pl':3.75,'pw':1.1})
r = requests.post(url,data)
print(r.json())

and i get this error: 
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-20-aaf3644d2890> in <module>()
      4 data = json.dumps({'sl':5.84,'sw':3.0,'pl':3.75,'pw':1.1})
      5 r = requests.post(url,data)
----> 6 print(r.json())

~/anaconda3/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    890                     # used.
    891                     pass
--> 892         return complexjson.loads(self.text, **kwargs)
    893 
    894     @property

~/anaconda3/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

~/anaconda3/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/anaconda3/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any help please. Thanks

**Comment by Quentame** [comment]
Issue solved, please create a new issue if still exists
