### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by hilaal** [picklepete/pyicloud#167]
Hi

api = PyiCloudService(xxxxxx@icloud.com', 'password')
api.files.dir()

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXXX/anaconda2/lib/python2.7/site-packages/pyicloud/services/ubiquity.py", line 48, in __getattr__
    return getattr(self.root, attr)
  File "/Users/XXXX/anaconda2/lib/python2.7/site-packages/pyicloud/services/ubiquity.py", line 44, in root
    self._root = self.get_node(0)
  File "/Users/XXXX/anaconda2/lib/python2.7/site-packages/pyicloud/services/ubiquity.py", line 25, in get_node
    return UbiquityNode(self, request.json())
  File "/Users/XXXX/anaconda2/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/XXXX/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/XXXX/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/XXXX/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by chadj** [comment]
The back-end for the files api changed awhile back and needs to be reimplemented.  pyicloud can't currently work with iCloud drive files.

See: #140
