### ISSUE TITLE
Error import PyiCloudService

### ISSUE THREAD

**Issue by fredrollin** [picklepete/pyicloud#181]
Hello,
I want to use Pyicloud but I have an issue.
I tried to install and after I made a python script

Just on line 
`from pyicloud import PyiCloudService`

And I have this error 
`Traceback (most recent call last):
  File "calendar.py", line 2, in <module>
    from pyicloud import PyiCloudService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/__init__.py", line 2, in <module>
    from pyicloud.base import PyiCloudService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 7, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 55, in <module>
    import urllib3
  File "/usr/lib/python2.7/dist-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 37, in <module>
    from .request import RequestMethods
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 6, in <module>
    from .filepost import encode_multipart_formdata
  File "/usr/lib/python2.7/dist-packages/urllib3/filepost.py", line 8, in <module>
    from .fields import RequestField
  File "/usr/lib/python2.7/dist-packages/urllib3/fields.py", line 1, in <module>
    import email.utils
  File "/usr/lib/python2.7/email/utils.py", line 32, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python2.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/pi/domoticz/scripts/python/calendar.py", line 2, in <module>
    from pyicloud import PyiCloudService
ImportError: cannot import name PyiCloudService`

Do you have an idea to help me?
Thank you for your help.
Fred

**Comment by grokkingStuff** [comment]
Hey Fred, how's it going?

So it looks like you have an issue with module imports - this is usually due to the installation of the package. I would recommend using pipenv as your package manager from now on. 

Pipenv works (Tested on June 06, 2018)

If you're unable to use Pipenv, please provide more information about your python setup.

Best of luck!
grokkingStuff

**Comment by fredrollin** [comment]
Hi grokkingStuff 
Thank you for your answer.

But I am a bigger in linux .

I use a raspberry. How can I install pyicloud with piping?

Thank you for your help.
Fred

**Comment by Suncatcher** [comment]
I have the same problem, is it workable with pip3 or pipenv is the only solution?

**Comment by Quentame** [comment]
Is the issue still happening with the new version ?

Here is code exemple : https://github.com/home-assistant/core/blob/dev/homeassistant/components/icloud/account.py
