### ISSUE TITLE
api.files.dir() Service Unavailable (503)

### ISSUE THREAD

**Issue by Vinz87** [picklepete/pyicloud#197]
I get the "pyicloud.exceptions.PyiCloudAPIResponseError: Service Unavailable (503)" error when I run "api.files.dir()".

Running "api.files" I get the object <pyicloud.services.ubiquity.UbiquityService object at 0xb639e250>

**Comment by Vinz87** [comment]
For me, the error is the exact one I reported (tried also right now), so I guess for you is a different issue perhaps related to a different problem.

**Comment by Quentame** [comment]
Please provide proper code exemple + logs where you get the error

**Comment by landall** [comment]
I get this error too. 

api.photos.all runs ok but api.files always 503.

**Comment by landall** [comment]
>>> api.files['com~apple~Notes']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyicloud\services\ubiquity.py", line 51, in __getitem__
    return self.root[key]
  File "C:\Python27\lib\site-packages\pyicloud\services\ubiquity.py", line 44, in root
    self._root = self.get_node(0)
  File "C:\Python27\lib\site-packages\pyicloud\services\ubiquity.py", line 24, in get_node
    request = self.session.get(self.get_node_url(id))
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\pyicloud\base.py", line 84, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Python27\lib\site-packages\pyicloud\base.py", line 132, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Service Unavailable (503)

**Comment by landall** [comment]
The other apple id show such a result:
api.files.dir()
[u'com~apple~TextInput', u'com~apple~shoebox']

not contain api.files['com~apple~Notes'].

I guess this may be caused by icloud data update to match new version of iOS?

**Comment by dsouzarc** [comment]
@landall Can you try that again? I'm still having the `503 Service Unavailable` issue and made a new Issue about it: [https://github.com/picklepete/pyicloud/issues/282](https://github.com/picklepete/pyicloud/issues/282)

**Comment by osheanlee** [comment]
having the same problem too :(
