### ISSUE TITLE
get photos error

### ISSUE THREAD

**Issue by huangbiyong** [picklepete/pyicloud#201]
![image](https://user-images.githubusercontent.com/16833275/53783567-15a9ec00-3f4d-11e9-88e9-b1d63877d394.png)

```shell
Traceback (most recent call last):
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/chhu02/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

During handling of the above exception, another exception occurred:

```shell
Traceback (most recent call last):
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x110991e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
```

During handling of the above exception, another exception occurred:

```shell
Traceback (most recent call last):
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='p38-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&clientId=C81D97C2-3F09-11E9-8287-787B8AC79CBE&dsid=8333902237 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110991e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

During handling of the above exception, another exception occurred:

```shell
Traceback (most recent call last):
  File "/Users/chhu02/Desktop/icloud/test.py", line 27, in <module>
    print(api.photos.all())
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/pyicloud/base.py", line 304, in photos
    self.params
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/pyicloud/services/photos.py", line 30, in __init__
    params=self.params
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chhu02/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p38-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&clientId=C81D97C2-3F09-11E9-8287-787B8AC79CBE&dsid=8333902237 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110991e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by Suncatcher** [comment]
I suppose this error is similar to my issue #200, they should be merged

**Comment by Quentame** [comment]
Have you tried with other services ?

Does this issue still happening with the new version ?

I don't think it's linked to the photo services since I also got this with find my iPhone, I think it's linked to the frequency you are fetching.

**Comment by Quentame** [comment]
Duplicates of #200
