### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by roudger** [picklepete/pyicloud#202]
Since a few months, I can not recover contacts from iCloud:

> python3 iCloudContactsToFile.py
Traceback (most recent call last):
  File "iCloudContactsToFile.py", line 15, in <module>
    addressbook = api.contacts.all()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyicloud-0.9.1-py3.5.egg/pyicloud/services/contacts.py", line 52, in all
    self.refresh_client()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyicloud-0.9.1-py3.5.egg/pyicloud/services/contacts.py", line 41, in refresh_client
    self.session.post(self._contacts_changeset_url, params=params_refresh)
  File "/Users/benjamin/Library/Python/3.5/lib/python/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyicloud-0.9.1-py3.5.egg/pyicloud/base.py", line 99, in request
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Bad Request (400)

How can I diagnose?
Thanks

**Comment by Waha-Liu88** [comment]
hi, budy, are u solved this problem？

**Comment by roudger** [comment]
Hi,
no, always the same problem

**Comment by sameerbarretto** [comment]
I'm getting the same thing if I make a call to `api.contacts.all()`.
I'm unable to figure out how to access this `api.contacts` object.
```
>>> api.contacts
<pyicloud.services.contacts.ContactsService object at 0x10>
```
