### ISSUE TITLE
Reminder - KeyError: 'description'

### ISSUE THREAD

**Issue by lidaobing** [picklepete/pyicloud#211]
```
>>> a = api.reminders
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyicloud/base.py", line 321, in reminders
    return RemindersService(service_root, self.session, self.params)
  File "/usr/local/lib/python3.7/site-packages/pyicloud/services/reminders.py", line 18, in __init__
    self.refresh()
  File "/usr/local/lib/python3.7/site-packages/pyicloud/services/reminders.py", line 59, in refresh
    if reminder['description']:
KeyError: 'description'
```

**Comment by MDolega20** [comment]
i got this problem too :/ how to fix this?
