### ISSUE TITLE
Error 450 (Authentication Needed) causes Python Recursion Error (Solved)

### ISSUE THREAD

**Issue by gcobb321** [picklepete/pyicloud#277]
## Environment

- pyiCloud release with the issue (`pip show pyicloud`): All versions
- Last working pyiCloud release (if known): Never worked
- Service causing this issue: PyiCloudSession/request function (base.py module)
- Python version (`python -V`): 3.7
- Operating environment (project deps/Docker/Windows/etc.): HassOS

## Traceback/Error logs
```
2020-04-18 12:59:24 INFO (SyncWorker_4) [custom_components.icloud3_dev.pyicloud_ic3] (request) method=POST, url=https://p58-fmipweb.icloud.com:443/fmipservice/client/web/refreshClient, kwargs={'data': '{"clientContext": {"fmly": true, "shouldLocate": true, "selectedDevice": "all", "deviceListVersion": 1}}', 'json': None, 'params': {'clientBuildNumber': '17DHotfix5', 'clientMasteringNumber': '17DHotfix5', 'ckjsBuildVersion': '17DProjectDev77', 'ckjsVersion': '2.0.5', 'clientId': 'A858BEF6-8190-11EA-A30F-DCA632132871', 'dsid': '186297810'}}
2020-04-18 12:59:24 WARNING (SyncWorker_4) [custom_components.icloud3_dev.pyicloud_ic3.http]  (450). Retrying ...
2020-04-18 12:59:24 INFO (SyncWorker_4) [custom_components.icloud3_dev.pyicloud_ic3] (request) method=POST, url=https://p58-fmipweb.icloud.com:443/fmipservice/client/web/refreshClient, kwargs={'data': '{"clientContext": {"fmly": true, "shouldLocate": true, "selectedDevice": "all", "deviceListVersion": 1}}', 'json': None, 'params': {'clientBuildNumber': '17DHotfix5', 'clientMasteringNumber': '17DHotfix5', 'ckjsBuildVersion': '17DProjectDev77', 'ckjsVersion': '2.0.5', 'clientId': 'A858BEF6-8190-11EA-A30F-DCA632132871', 'dsid': '186297810'}}

...

2020-04-18 12:59:24 WARNING (SyncWorker_4) [custom_components.icloud3_dev.pyicloud_ic3.http]  (450). Retrying ...
2020-04-18 12:59:24 INFO (SyncWorker_4) [custom_components.icloud3_dev.pyicloud_ic3] (request) method=POST, url=https://p58-fmipweb.icloud.com:443/fmipservice/client/web/refreshClient, kwargs={'data': '{"clientContext": {"fmly": true, "shouldLocate": true, "selectedDevice": "all", "deviceListVersion": 1}}', 'json': None, 'params': {'clientBuildNumber': '17DHotfix5', 'clientMasteringNumber': '17DHotfix5', 'ckjsBuildVersion': '17DProjectDev77', 'ckjsVersion': '2.0.5', 'clientId': 'A858BEF6-8190-11EA-A30F-DCA632132871', 'dsid': '186297810'}}
2020-04-18 12:59:24 ERROR (SyncWorker_4) [custom_components.icloud3_dev.device_tracker] maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/config/custom_components/icloud3_dev/device_tracker.py", line 2842, in _request_pyicloud_data_refresh
    self.famshr_api_device_ids.refresh_client()
  File "/config/custom_components/icloud3_dev/pyicloud_ic3.py", line 503, in refresh_client
    "deviceListVersion": 1,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3_dev/pyicloud_ic3.py", line 119, in request
    return self.request(method, url, **kwargs)
  File "/config/custom_components/icloud3_dev/pyicloud_ic3.py", line 119, in request
    return self.request(method, url, **kwargs)
  File "/config/custom_components/icloud3_dev/pyicloud_ic3.py", line 119, in request
    return self.request(method, url, **kwargs)
  [Previous line repeated 478 more times]
  File "/config/custom_components/icloud3_dev/pyicloud_ic3.py", line 99, in request
    response = super(PyiCloudSession, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 330, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/local/lib/python3.7/http/client.py", line 224, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/usr/local/lib/python3.7/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/local/lib/python3.7/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/usr/local/lib/python3.7/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/local/lib/python3.7/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/local/lib/python3.7/email/feedparser.py", line 224, in _parsegen
    for line in self._input:
  File "/usr/local/lib/python3.7/email/feedparser.py", line 129, in __next__
    line = self.readline()
  File "/usr/local/lib/python3.7/email/feedparser.py", line 89, in readline
    for ateof in reversed(self._eofstack):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

## Additional information
The following is a portion of the `request` function in base.py:
```
56    def request(self, method, url, **kwargs):  # pylint: disable=arguments-differ
57
58        # Charge logging to the right service endpoint
59        callee = inspect.stack()[2]
60        module = inspect.getmodule(callee[0])
61        request_logger = logging.getLogger(module.__name__).getChild("http")
62        if self.service.password_filter not in request_logger.filters:
63            request_logger.addFilter(self.service.password_filter)
64
65        request_logger.debug("%s %s %s", method, url, kwargs.get("data", ""))
66
67        kwargs.pop("retried", None)
68        response = super(PyiCloudSession, self).request(method, url, **kwargs69)
70
71        content_type = response.headers.get("Content-Type", "").split(";")[0]
72        json_mimetypes = ["application/json", "text/json"]
73
74        if not response.ok and content_type not in json_mimetypes:
75            if kwargs.get("retried") is None and response.status_code == 450:
76                api_error = PyiCloudAPIResponseException(
77                    response.reason, response.status_code, retry=True
78                )
79                request_logger.warn(api_error)
80                kwargs["retried"] = True
81                return self.request(method, url, **kwargs)
82            self._raise_error(response.status_code, response.reason)
```
When the error 450 occurs, the code passes the if statements (lines 74-75) and executes the `api_error...` code (lines 76-81). It then sets `kwargs["retried"] = True` (line 80) and runs the request function again. It is suppose to run this retry once (assumption) and raise an error (line 82) if the retry fails. However, the `kwargs.pop("retried", None)` (line 67) deletes `kwargs['retried`] item from the kwargs so it is always None when it executes the 'api_error...` code (lines 76-81) and the error retry loop is always excuted until a Pytho RecursionError is generated. It never falls through to the `self._raise_error...` (line 82) to generate the PyiCloudAPIResponseException error that can be caught by the calling program.

## Solution
1. Add the statement `kwargs_retry_flag = kwargs.get("retried", None)` before the `kwargs.pop("retried", None)` (line 65) to capture the current retry flag before it is deleted from kwargs.
2. Change the if statment on line 76 to check for that variable instead of the `kwargs.get['retried"]` (which doesn't exist due to the kwargs.pop statement). It will now read `if kwargs.get("retried") is None and response.status_code == 450:`.
The error loop wil now retry 1 time before falling through to the `self._raise_error...` (line 82) and generate the PyiCloudAPIResponseException error that can be caught by the calling program.

The code will now be:
```
...
**         kwargs_retry_flag = kwargs.get("retried", None)
67        kwargs.pop("retried", None)
68        response = super(PyiCloudSession, self).request(method, url, **kwargs69)
70
71        content_type = response.headers.get("Content-Type", "").split(";")[0]
72        json_mimetypes = ["application/json", "text/json"]
73
74        if not response.ok and content_type not in json_mimetypes:
**            if kwargs_retry_flag is None and response.status_code == 450:
...
```

**Comment by Quentame** [comment]
Thanks for it, actually happens in HA now :grimacing: 

Will check later tonight or tomorrow

**Comment by gcobb321** [comment]
I found it in a fork from last weekend on the actual 450 error but never 
got another 450 error. I was able to duplicate it with a lot of special 
debug code, which lead to the solution. It think it has always been 
there but never showed up by authenticating every time. I went 2 days 
with out doing an authentication and have changed iCoud3 to only do one 
every night at midnight. I am trapping the error in case it is needed 
during the day.

FYI-I put a counter and timer in the iCloud3 code that calls pyicloud to 
get some performance stats and it appears that eliminating the 
authentication every time cut the transactions to Apple Web Svcs in half 
and reduced the average transaction time from about 1.2+ secs for the 
authentication/api.device calls to about .50 secs with only the 
api.device call. This can be significant since iCloud3 can request 
location updates every 15-secs when approaching a zone, especially in a 
poor cell area.

Gary

------ Original Message ------

**Comment by gcobb321** [comment]
One other thing I noticed this afternoon after getting a 450 error is the response.reason is not available since nothing except the 450 code is returned from Apple Web Services. Since that is passed to the routine that generates the error message, all you see in the HA log file and on the developers tool/log screen is ‘(450)’ followed by ‘Retrying ...’. I added a message=‘Apple Web Server error, Authentication needed’ and pass that to the routine that generates the error message. What you now see in the log is ‘Apple Web Server error, Authentication needed (450)’.

**Comment by Quentame** [comment]
Yeah, but while we are retrying only once, it's fine
