### ISSUE TITLE
AlbumNameEnc error

### ISSUE THREAD

**Issue by pensphreak** [picklepete/pyicloud#285]
## The problem
I’m trying to use pyiCloud to download photos to my Ubuntu-based PC but I get an error with AlbumNameEnc

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 0.9.7
- Last working pyiCloud release (if known): unknown, my script stopped working around Feb 28, 2020
- Service causing this issue: 
- Python version (`python -V`): 3.8
- Operating environment (project deps/Docker/Windows/etc.): Latest Ubuntu, using icloud_photo_downloader as a front-end

## Traceback/Error logs

```shell

pens@gerbil:~/icloud_photos_downloader$ python3 icloudpd.py -d ~/iCloudPhotos --username=Xxxxx --password=Xxxxx
2020-06-30 08:58:19 DEBUG    Authenticating...
Traceback (most recent call last):
  File "icloudpd.py", line 5, in <module>
    main()
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pens/icloud_photos_downloader/icloudpd/base.py", line 276, in main
    photos = icloud.photos.albums[album]
  File "/home/pens/.local/lib/python3.8/site-packages/pyicloud/services/photos.py", line 186, in albums
    folder["fields"]["albumNameEnc"]["value"]
KeyError: 'albumNameEnc'

```

**Comment by pensphreak** [comment]
Turns out I had a weird ‘Untitled’/null album with no name and no photos in it.  I deleted that and everything seems to be running now.

**Comment by Quentame** [comment]
Hey !
So do you think we should close this or guard the key ?

**Comment by jfburdet** [comment]
I have the same error. I believe one should render pyicloud more robust for this kind of errors. I'll dig into this in a few days and try to submit a fix

**Comment by Quentame** [comment]
> Turns out I had a weird ‘Untitled’/null album with no name and no photos in it. I deleted that and everything seems to be running now.

What did you delete ?

**Comment by landall** [comment]
Is this patch released to PIP?
