### ISSUE TITLE
Photos: Download large videos get OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by muhammadmuhlas** [picklepete/pyicloud#292]
## The problem

I tried to download all of my photos, when downloading videos with the size of 3GB it returned an exception`OverflowError: signed integer is greater than maximum`

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 0.9.7
- Last working pyiCloud release (if known): 
- Service causing this issue: photos
- Python version (`python -V`): Python 3.8.1
- Operating environment (project deps/Docker/Windows/etc.): MacOS 10.15.5 with pipenv

## Traceback/Error logs

```shell
`Traceback (most recent call last):
  File "/Users/muhammadmuhlas/PycharmProjects/icloud/main.py", line 105, in <module>
    opened_file.write(download.raw.read())
  File "/Users/muhammadmuhlas/.local/share/virtualenvs/icloud-cZ-yrgb-/lib/python3.8/site-packages/urllib3/response.py", line 514, in read
    data = self._fp.read() if not fp_closed else b""
  File "/Users/muhammadmuhlas/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 467, in read
    s = self._safe_read(self.length)
  File "/Users/muhammadmuhlas/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 608, in _safe_read
    data = self.fp.read(amt)
  File "/Users/muhammadmuhlas/.pyenv/versions/3.8.1/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/muhammadmuhlas/.pyenv/versions/3.8.1/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/muhammadmuhlas/.pyenv/versions/3.8.1/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum`
```

## Additional information
Code:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/5829261/89722706-01f29700-da17-11ea-95a0-8eed2a29cc5f.png">

Debugger:
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/5829261/89722717-19318480-da17-11ea-9b22-a4a1afae1c20.png">

**Comment by muhammadmuhlas** [comment]
This issue solved by iterating the chunk using `request.iter_content`
![image](https://user-images.githubusercontent.com/5829261/99009567-cf5abc00-257a-11eb-9dc3-02b7a89019d1.png)
