### ISSUE TITLE
JSONDecodeError when running `api.files.dir()`

### ISSUE THREAD

**Issue by kolaente** [picklepete/pyicloud#293]
## The problem

Running `api.files.dir()` gives me a `JSONDecoderError` (see below for full trace):

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This seems to be related to #140 which has been resolved two years ago so I figured I'd better open a new issue.

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 0.9.7 through nixpkgs (`python38Packages.pyicloud`)
- Last working pyiCloud release (if known): 
- Service causing this issue: 
- Python version (`python -V`): 3.8.3
- Operating environment (project deps/Docker/Windows/etc.): Linux/NixOS

## Traceback/Error logs

```shell
>>> api.files.dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/hg9fx9178yb4hclbw6i2iwpmdim9chs2-python3.8-pyicloud-0.9.1/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 48, in __getattr__
    return getattr(self.root, attr)
  File "/nix/store/hg9fx9178yb4hclbw6i2iwpmdim9chs2-python3.8-pyicloud-0.9.1/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 44, in root
    self._root = self.get_node(0)
  File "/nix/store/hg9fx9178yb4hclbw6i2iwpmdim9chs2-python3.8-pyicloud-0.9.1/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 25, in get_node
    return UbiquityNode(self, request.json())
  File "/nix/store/vc5xl372g3kl81ffzncjqn75ghwb2k9s-python3.8-requests-2.22.0/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/vycrjvqsg1f5plflf4mq4f2i2y31l76i-python3-3.8.3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/vycrjvqsg1f5plflf4mq4f2i2y31l76i-python3-3.8.3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/vycrjvqsg1f5plflf4mq4f2i2y31l76i-python3-3.8.3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kolaente** [comment]
As it turns out, I did not pay attention to the 2fa code I needed. Once I entered that, it worked as intended.

I think the error message in that case could be improved but that's probably a seperate issue.
