### ISSUE TITLE
Unable to request Event information

### ISSUE THREAD

**Issue by ajjack50n** [picklepete/pyicloud#322]
## The problem

Hi...

Trying to access events does not work on the latest version - at least for me. 

```
print("Events")
print(api.calendar.events())
from_dt = datetime.date(2018, 1, 1)
to_dt = datetime.date(2018, 1, 31)
print(api.calendar.events(from_dt, to_dt))

```

this code results in the error 

`pyicloud.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)`

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 0.10.2
- Last working pyiCloud release (if known): 
- Service causing this issue: Events
- Python version (`python -V`): 3.8
- Operating environment (project deps/Docker/Windows/etc.): mac

## Traceback/Error logs

```shell
Traceback (most recent call last):
  File "/Users/andy/Python Development/FamilyTicker/test.py", line 53, in <module>
    print(api.calendar.events(from_dt, to_dt))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyicloud/services/calendar.py", line 65, in events
    self.refresh_client(from_dt, to_dt)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyicloud/services/calendar.py", line 58, in refresh_client
    req = self.session.get(self._calendar_refresh_url, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyicloud/base.py", line 128, in request
    return self.request(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyicloud/base.py", line 130, in request
    self._raise_error(response.status_code, response.reason)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyicloud/base.py", line 186, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)
```

## Additional information
Others services all seem to work. Id just Events that seems to have a problem.

**Comment by oleg-agapov** [comment]
Having the same issue with Calendar. 

2FA went well, other APIs seems to be working (checked with devices).

**Comment by Soneji** [comment]
@Quentame is there any update on this? I am unable to use this project because of this error which affects calendar, reminders, and possibly more!

**Comment by Anteloper** [comment]
Same here

**Comment by dgmiller81** [comment]
I have the same issue with calendar events.  Anyone have any updates on this at all?

**Comment by zarkin404** [comment]
A duplicate of #330, there is a solution you guys can try.

**Comment by zarkin404** [comment]
[pyicloud.zip](https://github.com/picklepete/pyicloud/files/7775084/pyicloud.zip)

I have finished a simple demo to fetch all notes inspired by @MauriceConrad 's project [iCloud-API](https://github.com/MauriceConrad/iCloud-API)

You can use the following code to get the notes:

```
    api = PyiCloudService(username, password)
    for note in api.notes.records:
        print(note["fields"]["Text"])
```

I just changed `base.py`, and added `services/notes.py`, `protobuf` to added this feature.

Hope you guy like it.
