### ISSUE TITLE
iCloud drive commands lead to key error

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [picklepete/pyicloud#326]
When I try to delete a file

`api.drive['test'].delete()`

the following error shows up:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyicloud/services/drive.py", line 294, in delete
    return self.connection.move_items_to_trash(
  File "pyicloud/services/drive.py", line 184, in move_items_to_trash
    "clientId": self.params["clientId"],
KeyError: 'clientId'
```

I fixed it by passing client_id from base to the drive service. Looks like clientId is not present in the params dict.

**Comment by alschrm** [comment]
I'm having the same issue! Could you clarify "passing client_id from base to the drive service" ?

**Comment by alschrm** [comment]
It seems that .rename() is working, and I was ultimately able to use that as a workaround. Basically moving the file into an archive folder when I'm done processing it with something like this:

`api = PyiCloudService(usr_apple,pwd_apple)
`drive_file=api.drive['file.rtf']
`drive_file.rename('/arch/file.rtf')
`

**Comment by volderette** [comment]
I have the same problem with the mkdir command. @Unkn0wn-MDCLXIV , can you tell me more about your workaround?

**Comment by everdrone** [comment]
I'm having the same problems with `delete()` can somebody share the workaround?

**Comment by honzajavorek** [comment]
Meanwhile, this works as a patch:

```python
from pyicloud import PyiCloudService as _PyiCloudService
from pyicloud.base import DriveService

class PyiCloudService(_PyiCloudService):
    # patch: https://github.com/picklepete/pyicloud/pull/359/files
    @_PyiCloudService.drive.getter
    def drive(self):
        if not self._drive:
            if not 'clientId' in self.params:
                self.params['clientId'] = self.client_id
            self._drive = DriveService(
                service_root=self._get_webservice_url("drivews"),
                document_root=self._get_webservice_url("docws"),
                session=self.session,
                params=self.params,
            )
        return self._drive
```

In the following code you can use `PyiCloudService` as if https://github.com/picklepete/pyicloud/pull/359/ was already merged.

**Comment by yuima** [comment]
@honzajavorek 
Thank you for your great work!
It works well in my environment.

**Comment by ryankrawz** [comment]
You can also explicitly set the client ID without editing the source if you prefer:
```python
client_id = 'auth-%s' % str(uuid1()).lower()
api = PyiCloudService('myusername', 'mypassword', client_id=client_id)
api.params['clientId'] = client_id
```
