### ISSUE TITLE
Ubiquity key error dsid

### ISSUE THREAD

**Issue by zimo-github** [picklepete/pyicloud#333]
## The problem

print(api.files.dir()) throws a key error:

  File "/Users/zimo/pyicloud/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 43, in __getattr__
    return getattr(self.root, attr)
  File "/Users/zimo/pyicloud/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 20, in root
    self._root = self.get_node(0)
  File "/Users/zimo/pyicloud/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 29, in get_node
    request = self.session.get(self.get_node_url(node_id))
  File "/Users/zimo/pyicloud/lib/python3.8/site-packages/pyicloud/services/ubiquity.py", line 25, in get_node_url
    return self._node_url % (self.params["dsid"], variant, node_id)
KeyError: 'dsid'

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 0.10.2
- Last working pyiCloud release (if known): -/-
- Service causing this issue: Ubiquity
- Python version (`python -V`): 3.8.2
- Operating environment (project deps/Docker/Windows/etc.): Mac OS Big Sur 11.2.3

## Traceback/Error logs

```shell

```

## Checklist

- [x] I've looked informations into the README.
- [x] I've looked informations into the pyiCloud's code.
- [x] I've looked informations in Google.

## Additional information
Login and 2FA works fine, I can access iCloud Drive file info and device listing without errors.
The error persists when I switch to python 3.9.4.
Thanks a lot in advance for any help!
Regards
Thomas

**Comment by Krammy** [comment]
The same problem occuring on Windows 10 too, returning `KeyError: dsid` when trying to access `api.files.dir()`.
Any ideas on how to fix this?

**Comment by zimo-github** [comment]
Sorry, didn’t have time to look into this in the meantime.

**Comment by ZhangTianrong** [comment]
It seems that `pyicloud` never attempts to retrieve the `dsid` or does it? What if I provide this in `param` manually? I will give it a try and report my findings here I guess.

**Comment by Krammy** [comment]
Maybe this will be helpful for people, though I started using the SimpleNote app for note collection and reading instead. [There's a Python API you can use for this](https://pypi.org/project/simplenote/).

**Comment by moll** [comment]
For those looking for a quick fix, get the DSID of yourself from the family member list (`api.account.family`) and pass it to `api.files`'s UbiquityService:

```python
api.files.params["dsid"] = api.account.family[0].dsid
```

**Comment by zimo-github** [comment]
Thanks a lot for the quick fix! Got a 503 Service unavailable today but I'm going to check that from time to time again.

**Comment by shr00mie** [comment]
to piggyback on @moll's post, if you don't have the family service:

```python
api.files.params['dsid'] = api.data['dsInfo']['dsid']
```

**Comment by borismus** [comment]
Seeing this exact thing. Wondering if maybe it's because of some iCloud family stuff? Super bummed, since the rest of the library works great, and this seems to be a nice sane programatic way to access iCloud Drive files :(

**Comment by osheanlee** [comment]
following this too. still encountering this problem

**Comment by idiamant** [comment]
I also encounter errors with this. When setting up dsid manually as:
api.files.params['dsid'] = api.data['dsInfo']['dsid']

I now get Bad Request (400) when trying to use api.files.dir()
```
api.files.dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/idod/.virtualenvs/venv3/lib/python3.9/site-packages/pyicloud/services/ubiquity.py", line 97, in dir
    return [child.name for child in self.get_children()]
  File "/Users/idod/.virtualenvs/venv3/lib/python3.9/site-packages/pyicloud/services/ubiquity.py", line 92, in get_children
    self._children = self.connection.get_children(self.item_id)
  File "/Users/idod/.virtualenvs/venv3/lib/python3.9/site-packages/pyicloud/services/ubiquity.py", line 33, in get_children
    request = self.session.get(self.get_node_url(node_id, "parent"))
  File "/Users/idod/.virtualenvs/venv3/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/idod/.virtualenvs/venv3/lib/python3.9/site-packages/pyicloud/base.py", line 133, in request
    self._raise_error(response.status_code, response.reason)
  File "/Users/idod/.virtualenvs/venv3/lib/python3.9/site-packages/pyicloud/base.py", line 189, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Bad Request (400)
```

**Comment by miku** [comment]
If I'm printing out the URL of the request - from `api.files.dir()` - that yields a 503 I get something like:

```
https://p09-ubiquityws.icloud.com:443/ws/123123123/item/0
```

The Content-Length is 23 bytes and says:

```
Account migrated
```

**Comment by despian** [comment]
Also getting 503 after manually setting did.

Has anyone managed to resolve this?

**Comment by a-hydrae** [comment]
Found an answer: [https://developer.apple.com/library/archive/technotes/tn2348/_index.html](https://developer.apple.com/library/archive/technotes/tn2348/_index.html)

**Comment by MShirazAhmad** [comment]
Did anyone find a solution to this?
