### ISSUE TITLE
Can't logging in AssertionError

### ISSUE THREAD

**Issue by beckietech** [picklepete/pyicloud#335]
## when I use icloud --username myusername --password mypassword, after typing in 2fa code, the error msg:
Save password in keyring?  [y/N]: N
Two-step authentication required. Your trusted devices are:
  0: SMS to *******20
Which device would you like to use? [0]: 0
Please enter validation code: 887799
Traceback (most recent call last):
  File "/usr/local/bin/icloud", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pyicloud_ipd/cmdline.py", line 253, in main
    for dev in api.devices:
  File "/usr/local/lib/python3.5/dist-packages/pyicloud_ipd/base.py", line 298, in devices
    self.params
  File "/usr/local/lib/python3.5/dist-packages/pyicloud_ipd/services/findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "/usr/local/lib/python3.5/dist-packages/pyicloud_ipd/services/findmyiphone.py", line 67, in refresh_client
    raise PyiCloudNoDevicesException()
pyicloud_ipd.exceptions.PyiCloudNoDevicesException

## Environment

Im using it on Debian 9
- pyiCloud release with the issue (`pip show pyicloud`): 
- Last working pyiCloud release (if known): 
- Service causing this issue: 
- Python version (`python -V`): 
- Operating environment (project deps/Docker/Windows/etc.): 

## Traceback/Error logs

```shell

```

**Comment by Krammy** [comment]
It looks like you're trying to call `api.files` too, consider merging with this thread:
https://github.com/picklepete/pyicloud/issues/333
