### ISSUE TITLE
RemoteWipe using findMyiPhone Library

### ISSUE THREAD

**Issue by truejp** [picklepete/pyicloud#341]
## The problem

Hey,
I'm trying to get remoteWipe (Erase my iPhone) up and running using this awesome Lib. I extended the findmyiphone.py library with the endpoint of remoteWipe:

`self._fmip_wipe_url = "%s/remoteWipe" % fmip_endpoint`

The endpoint "should" be the right one, there are some older php libs using this one:
[https://github.com/tylerhall/sosumi/blob/master/class.sosumi.php#L101-L109](url)
[https://github.com/Neal/FindMyiPhone/blob/master/include/classes/FindMyiPhone.php#L261-L277](url)
I also added the neccessary parts to the refresh_Client() method 

`self._devices[device_id] = AppleDevice(
                    device_info,
                    self.session,
                    self.params,
                    manager=self,
                    sound_url=self._fmip_sound_url,
                    lost_url=self._fmip_lost_url,
                    wipe_url=self._fmip_wipe_url,
                    message_url=self._fmip_message_url,
                )`

and to the AppleDevice Class itself.

`def __init__(
        self,
        content,
        session,
        params,
        manager,
        sound_url=None,
        lost_url=None,
        wipe_url=None,
        message_url=None,
    ):
        self.content = content
        self.manager = manager
        self.session = session
        self.params = params

        self.sound_url = sound_url
        self.lost_url = lost_url
        self.wipe_url = wipe_url
        self.message_url = message_url`

I also wrote a method wipe_device:

`def wipe_device(
        self, text="Test", newpasscode=""
    ):
        """Send a request to the device to trigger 'remote wipe'.
        The device will be deleted (Hopefully....).
        """
        data = json.dumps(
            {
                "device": self.content["id"],
                "passcode": '000000',
                "text": 'Testtext',
                "emailUpdates": 'true',
            }
        )
        self.session.post(self.wipe_url, params=self.params, data=data)`

Now comes the fun part: whenever I trigger this functions, the Apple Server returns error code 501 (not implemented). I really hope someone could help me figure this out? I'd like to contribute the working code afterwards too.

## Environment

 I'm running the script using Windows 10 with Python 3.9.1 64 Bit and the latest Version of PyiCloud (0.10.2). I installed it using pip. The affected service is findmyiphone.

`Name: pyicloud
Version: 0.10.2
Summary: PyiCloud is a module which allows pythonistas to interact with iCloud webservices.
Home-page: https://github.com/picklepete/pyicloud
Author: None
Author-email: None
License: MIT
Location: c:\users\janle\appdata\local\programs\python\python39\lib\site-packages
Requires: keyring, tzlocal, keyrings.alt, requests, certifi, six, pytz, click, future
Required-by:`

- pyiCloud release with the issue (`pip show pyicloud`): 
- Last working pyiCloud release (if known): 
- Service causing this issue: 
- Python version (`python -V`): 
- Operating environment (project deps/Docker/Windows/etc.): 

## Traceback/Error logs
  `Traceback (most recent call last):
  File "C:\Users\janle\OneDrive\BL Consulting & Solutions\iPhone Tool\Script dev\icloud.py", line 53, in <module>
    api.devices[device-1].wipe_device("", "")
  File "C:\Users\janle\AppData\Local\Programs\Python\Python39\lib\site-packages\pyicloud\services\findmyiphone.py", line 209, in wipe_device
    self.session.post(self.wipe_url, params=self.params, data=data)
  File "C:\Users\janle\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\janle\AppData\Local\Programs\Python\Python39\lib\site-packages\pyicloud\base.py", line 130, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Users\janle\AppData\Local\Programs\Python\Python39\lib\site-packages\pyicloud\base.py", line 186, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException:  (501)`

```shell

```

## Checklist

- [x] I've looked informations into the README.
- [x] I've looked informations into the pyiCloud's code.
- [x] I've looked informations in Google.

**Comment by KovalevArtem** [comment]
Did you know about this authorization method? https://github.com/picklepete/pyicloud/issues/345
I think it will be useful for you ...

**Comment by truejp** [comment]
@KovalevArtem That's awesome, I'll dive deeper into this the next days and keep you updated - Thanks for sharing!
