### ISSUE TITLE
Devices functionalities not working after a few hours

### ISSUE THREAD

**Issue by zaironjacobs** [picklepete/pyicloud#346]
## The problem
After authenticating with 2FA, devices functionalities work fine, but after a few hours (not sure how many hours) they stop working (but If I try to get contacts for example it still works) and I start seeing the following when I try to get any device:

`
api.devices
`

Will throw:

`
pyicloud.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (450)
`

Anyone else having this issue?

## Environment
- Last working pyiCloud release (if known): -
- Service causing this issue: FindMyiPhoneServiceManager
- Python version (`python -V`): 3.9.1
- Operating environment (project deps/Docker/Windows/etc.): Windows and Linux (Ubuntu)

## Traceback/Error logs
```shell
Traceback (most recent call last):
  File "C:\Users\Zairon\PycharmProjects\pythonProject\main.py", line 7, in <module>
    api.devices
  File "C:\Users\Zairon\PycharmProjects\pythonProject\pyicloud\base.py", line 535, in devices
    return FindMyiPhoneServiceManager(
  File "C:\Users\Zairon\PycharmProjects\pythonProject\pyicloud\services\findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "C:\Users\Zairon\PycharmProjects\pythonProject\pyicloud\services\findmyiphone.py", line 36, in refresh_client
    req = self.session.post(
  File "C:\Users\Zairon\.virtualenvs\pythonProject-HdMtA4Xf\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Zairon\PycharmProjects\pythonProject\pyicloud\base.py", line 128, in request
    return self.request(method, url, **kwargs)
  File "C:\Users\Zairon\PycharmProjects\pythonProject\pyicloud\base.py", line 130, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Users\Zairon\PycharmProjects\pythonProject\pyicloud\base.py", line 186, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (450)
```

**Comment by DeeeeLAN** [comment]
I am having this issue after updating recently. Did you manage to fix it?

**Comment by zaironjacobs** [comment]
Had to do something like this in order to refresh the session when the problem occurs every time. Couldn't find a better solution that didn't require passing the cookie directory of the session and the email and password again.

`
PyiCloudService(apple_id=email, password=password, cookie_directory=pyicloud_cookie_dir, client_id=client_id)
`
