### ISSUE TITLE
unrecognized arguments: --store-in-keyring

### ISSUE THREAD

**Issue by esp32x** [picklepete/pyicloud#348]
## The problem
Missing or gone command line option for _icloud_
unrecognized arguments: --store-in-keyring

## Environment
- pyiCloud release with the issue (`pip show pyicloud`): Version: 0.10.2
- Last working pyiCloud release (if known): 
- Service causing this issue: command line
- Python version (`python -V`): Python 3.9.1
- Operating environment (project deps/Docker/Windows/etc.): macOS

## Traceback/Error logs
```python
api = PyiCloudService("user@example.com")
```

```python
Traceback (most recent call last):
  File "/Users/test/PycharmProjects/icloud/main.py", line 119, in <module>
    print_icloud('PyCharm')
  File "/Users/test/PycharmProjects/icloud/main.py", line 17, in print_icloud
    api = PyiCloudService("user@example.com")
  File "/Users/test/PycharmProjects/icloud/venv/lib/python3.9/site-packages/pyicloud/base.py", line 214, in __init__
    password = get_password_from_keyring(apple_id)
  File "/Users/test/PycharmProjects/icloud/venv/lib/python3.9/site-packages/pyicloud/utils.py", line 39, in get_password_from_keyring
    raise PyiCloudNoStoredPasswordAvailableException(
pyicloud.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for user@example.com could be found in the system keychain.  
Use the `--store-in-keyring` command-line option for storing a password for this username.

Process finished with exit code 1

```

Then I try
```shell
icloud --username=user@example.com --store-in-keyring
```
and get
```error
icloud: error: unrecognized arguments: --store-in-keyring
```

**Comment by dHumanities** [comment]
Same problem here.

**Comment by brandon-fryslie** [comment]
there is no cli argument for this.  It will prompt you to store the password in the keyring once you've successfully authenticated using the cli tool.

The code is here: https://github.com/picklepete/pyicloud/blob/master/pyicloud/cmdline.py#L205

Implementing a cli arg seems relatively trivial if it's important to anyone to have it.
