### ISSUE TITLE
new issue with connecting to icloud service with api = PyiCloudService

### ISSUE THREAD

**Issue by JayJayJanssen** [picklepete/pyicloud#351]
I have this python script that checks the location of my iphone and stores it on a regular base in a .csv file.
This is based on pyicloud and has been working robustly for more than 2 years.

This stopped working a few days ago for my apple account that does NOT have 2fa, not does it have 2sa. The account is password only based.

This is the python dump I get:

Traceback (most recent call last):
  File "/home/u30/.local/lib/python3.6/site-packages/pyicloud/base.py", line 345, in _authenticate_with_token
    "%s/accountLogin" % self.SETUP_ENDPOINT, data=json.dumps(data)
  File "/home/u30/.local/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/u30/.local/lib/python3.6/site-packages/pyicloud/base.py", line 157, in request
    self._raise_error(code, reason)
  File "/home/u30/.local/lib/python3.6/site-packages/pyicloud/base.py", line 186, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Missing apple_id field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myPyIcloud.py", line 300, in <module>
    main()
  File "myPyIcloud.py", line 276, in main
    api = PyiCloudService('hide', 'hide')
  File "/home/u30/.local/lib/python3.6/site-packages/pyicloud/base.py", line 268, in __init__
    self.authenticate()
  File "/home/u30/.local/lib/python3.6/site-packages/pyicloud/base.py", line 328, in authenticate
    self._authenticate_with_token()
  File "/home/u30/.local/lib/python3.6/site-packages/pyicloud/base.py", line 350, in _authenticate_with_token
    raise PyiCloudFailedLoginException(msg, error)
pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field',))

**Comment by JayJayJanssen** [comment]
resolved

**Comment by odelma** [comment]
Was there something particular you did? I can see something changed around Sep 20th. I have 2fa enabled but pyicloud does not invoke the prompt on my devices anymore…

**Comment by odelma** [comment]
Can you @JayJayJanssen share your resolution? 😃

**Comment by TangWilson** [comment]
@JayJayJanssen Can you share your solution please?  I have the same question.

**Comment by zefoo** [comment]
Same issue. Any solution? Odd, this used to work.
