### ISSUE TITLE
api.calendar.events() and api.files.dir() raise exception always!

### ISSUE THREAD

**Issue by wangxiya** [picklepete/pyicloud#380]
devices and location and contacts correct!
but calendar and files always failure!

Events
Traceback (most recent call last):
  File "/Users/wangxiya/Develop/app_ical/test.py", line 70, in <module>
    print(api.calendar.events())
  File "/Users/wangxiya/Develop/app_ical/venv/lib/python3.9/site-packages/pyicloud/services/calendar.py", line 64, in events
    self.refresh_client(from_dt, to_dt)
  File "/Users/wangxiya/Develop/app_ical/venv/lib/python3.9/site-packages/pyicloud/services/calendar.py", line 57, in refresh_client
    req = self.session.get(self._calendar_refresh_url, params=params)
  File "/Users/wangxiya/Develop/app_ical/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/wangxiya/Develop/app_ical/venv/lib/python3.9/site-packages/pyicloud/base.py", line 131, in request
    return self.request(method, url, **kwargs)
  File "/Users/wangxiya/Develop/app_ical/venv/lib/python3.9/site-packages/pyicloud/base.py", line 133, in request
    self._raise_error(response.status_code, response.reason)
  File "/Users/wangxiya/Develop/app_ical/venv/lib/python3.9/site-packages/pyicloud/base.py", line 189, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Authentication required for Account. (421)

**Comment by ACB-prgm** [comment]
I was having the same issue but got around it by manually calling the `calendar.refresh_client()` method before making my queries.
