### ISSUE TITLE
ImportError: cannot import name 'PyiCloudService' from partially initialized module 'pyicloud'

### ISSUE THREAD

**Issue by phiwop** [picklepete/pyicloud#420]
## The problem

Trying to import PyiCloudService not possible (maybe due to circular import). 

Code: 
from pyicloud import PyiCloudService
api = PyiCloudService("username","password")

giving:
ImportError: cannot import name 'PyiCloudService' from partially initialized module 'pyicloud' (most likely due to a circular import)

## Environment

1. Test Environment: Mac OS, Python 3.9.6 VENV - pip3 install pyicloud

Version: 1.0.0
Summary: PyiCloud is a module which allows pythonistas to interact with iCloud webservices.
Home-page: https://github.com/picklepete/pyicloud
Author: 
Author-email: 
License: MIT
Location: XXX/.venv/lib/python3.9/site-packages
Requires: certifi, click, keyring, keyrings.alt, requests, tzlocal
Required-by: 

3. RPi: Python 3.9.2, pip3 install pyicloud

Name: pyicloud
Version: 1.0.0
Summary: PyiCloud is a module which allows pythonistas to interact with iCloud webservices.
Home-page: https://github.com/picklepete/pyicloud
Author: None
Author-email: None
License: MIT
Location: /home/pi/.local/lib/python3.9/site-packages
Requires: requests, tzlocal, click, certifi, keyrings.alt, keyring
Required-by:

## Traceback/Error logs

```shell

Traceback (most recent call last):
  File "XXX/pyicloud.py", line 5, in <module>
    from pyicloud import PyiCloudService
  File "XXX/pyicloud.py", line 5, in <module>
    from pyicloud import PyiCloudService
ImportError: cannot import name 'PyiCloudService' from partially initialized module 'pyicloud' (most likely due to a circular import) (XXX/pyicloud.py)

```

**Comment by phiwop** [comment]
Sry, my mistake. Renamed my filename.
