### ISSUE TITLE
I get error on running api.files.dir()

### ISSUE THREAD

**Issue by john-saman** [picklepete/pyicloud#48]
> from pyicloud import PyiCloudService
> api = PyiCloudService('ID', 'password')
> api.files.dir()

{u'reason': u'Invalid global session', u'error': 2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyicloud/services/ubiquity.py", line 96, in dir
    return [child.name for child in self.get_children()]
  File "pyicloud/services/ubiquity.py", line 78, in get_children
    self._children = self.connection.get_children(self.item_id)
  File "pyicloud/services/ubiquity.py", line 35, in get_children
    items = request.json()['item_list']
KeyError: 'item_list'

**Comment by john-saman** [comment]
Notice the error at last line
> KeyError: 'item_list'

**Comment by torarnv** [comment]
Is this still an issue?

**Comment by torarnv** [comment]
Closed due to inactivity.
