### ISSUE TITLE
Calendar Retrieval Problem

### ISSUE THREAD

**Issue by Abolisher** [picklepete/pyicloud#71]
Hi,
Can anyone shed light on a problem I'm having accessing calendar and contact info.  I can connect ok and go through the two stage verification with no problems.  I can access info on devices, but when i try to print calendar.events() it fails:

New to this, so expect its something simple i haven't done?

Thanks in advance,  Rob

OUTPUT:
{u’***********’: <AppleDevice(iPhone 6 Plus: 7)>, u’***********': <AppleDevice(Mac mini: Cooper)>}

Traceback (most recent call last):
  File “iCloud”, line 26, in <module>
    print api.calendar.events()
  File "/Library/Python/2.7/site-packages/pyicloud-0.8.0-py2.7.egg/pyicloud/services/calendar.py", line 93, in events
    self.refresh_client(from_dt, to_dt)
  File "/Library/Python/2.7/site-packages/pyicloud-0.8.0-py2.7.egg/pyicloud/services/calendar.py", line 86, in refresh_client
    req = self.session.get(self._calendar_refresh_url, params=params)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/pyicloud-0.8.0-py2.7.egg/pyicloud/base.py", line 71, in request
    reason = json.get('errorMessage') or json.get('reason')
AttributeError: 'NoneType' object has no attribute 'get'

code:

> from pyicloud import PyiCloudService
> import click
> 
> api=PyiCloudService(‘******’,’******’)
> 
> if api.requires_2fa:
>     print "Two-factor authentication required. Your trusted devices are:"
> 
>     devices = api.trusted_devices
>     for i, device in enumerate(devices):
>         print "  %s: %s" % (i, device.get('deviceName',
>             "SMS to %s" % device.get('phoneNumber')))
> 
>     device = click.prompt('Which device would you like to use?', default=0)
>     device = devices[device]
>     if not api.send_verification_code(device):
>         print "Failed to send verification code"
>         sys.exit(1)
> 
>     code = click.prompt('Please enter validation code')
>     if not api.validate_verification_code(device, code):
>         print "Failed to verify verification code"
>         sys.exit(1)
> 
> print api.devices
> print api.calendar.events()

**Comment by torarnv** [comment]
I see what the issue is, I'll prepare a fix as soon as I can.

**Comment by Bart274** [comment]
I'm having this issue with the calendar retrieval:
```
16-03-11 16:48:27 homeassistant.bootstrap: Error during setup of component icloud
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\homeassistant-0.15.0.dev0-py3.4.egg\homeassistant\bootstrap.py", line 106, in _setup_component
    if not component.setup(hass, config):
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\custom_components\icloud.py", line 81, in setup
    ignored_devices)
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\custom_components\icloud.py", line 423, in __init__
    events = self.api.calendar.events()
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\lib\pyicloud\services\calendar.py", line 97, in events
    self.refresh_client(from_dt, to_dt)
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\lib\pyicloud\services\calendar.py", line 86, in refresh_client
    'usertz': self.get_system_tz(),
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\lib\pyicloud\services\calendar.py", line 53, in get_system_tz
    return self.get_all_possible_timezones_of_local_machine()[0]
IndexError: list index out of range
```

**Comment by torarnv** [comment]
@Bart274 Please file a separate issue for that.

**Comment by Bart274** [comment]
@torarnv I created a PR instead :)
