### ISSUE TITLE
Fetch Asset Data Error

### ISSUE THREAD

**Issue by LesBlake** [picklepete/pyicloud#99]
Any time I attempt to fetch anything other than id I get the following error:
`
>>> for photo in api.photos.all:                                                                                                                                                                                               
print(photo, photo.filename)
                                                                                                                                                                                            Traceback (most recent call last):                                                                                                                                                                                          
    File "<stdin>", line 2, in <module>
    File "/usr/lib/python3.5/site-packages/pyicloud-0.9.1-py3.5.egg/pyicloud/services/photos.py", line 242, in filename
        return self.data['details'].get('filename')
    File "/usr/lib/python3.5/site-packages/pyicloud-0.9.1-py3.5.egg/pyicloud/services/photos.py", line 237, in data self._data = self.album._fetch_asset_data_for(self)
    File "/usr/lib/python3.5/site-packages/pyicloud-0.9.1-py3.5.egg/pyicloud/services/photos.py", line 203, in _fetch_asset_data_forclient_ids.append(self._photo_assets[index].client_id)
TypeError: 'dict_values' object does not support indexing
`
I'm probably just doing something wrong, any help would be appreciated.

**Comment by torarnv** [comment]
Python 3 issue, fixed in 801ee8f7f7.
